apiVersion: v1
kind: ConfigMap
metadata:
  name: charlie-addons-worker-config
  namespace: charlie-addons-prod
data:
  APP_TITLE: "Charlie Addons Worker API"
  APP_DESCRIPTION: "Worker API service for Charlie Mail"
  APP_VERSION: "1.0.0"
  RABBITMQ_USER: "user"
  RABBITMQ_PASSWORD: "bitnami"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  GRAPH_API: "http://charlie-addons-graph:8003"
  DEBUGGER: "False"
  ENVIRONMENT: "dev"
  WORKER_ROUTER: "app.worker.intake.init_worker_intake"
  QUEUE_INTAKE: "ltl"
