apiVersion: v1
kind: Service
metadata:
  name: charlie-addons-worker-service
  namespace: charlie-addons-prod
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    role: charlie-addons-worker-service
